//! Native provider CRUD against the disposable integration environment only.
use anyhow::{Context, Result, ensure};
use serde_json::{Value, json};
use std::path::Path;

fn instance<'a>(snapshot: &'a Value, id: &str) -> Result<&'a Value> {
    snapshot["instances"]
        .as_array()
        .context("missing provider list")?
        .iter()
        .find(|row| row["instanceId"] == id)
        .context("fixture provider missing")
}

#[tokio::main]
async fn main() -> Result<()> {
    let path = std::env::args()
        .nth(1)
        .context("providers <isolated-connection.json>")?;
    let connection: Value = serde_json::from_slice(&std::fs::read(&path)?)?;
    ensure!(
        connection["origin"] == "http://127.0.0.1:39741",
        "use the isolated test server"
    );
    let client = zeron_rpc::memory_client(zeron_t3::T3Service::connect(Path::new(&path)).await?);
    let original = client.call("T3ProvidersGet", json!({})).await?;
    let id = format!("z3_qa_{}", uuid::Uuid::new_v4().simple());
    let desired = json!({"driver":"pi","displayName":"Native provider QA","enabled":false,
        "config":{"binaryPath":"/nonexistent/z3-provider-fixture","customModels":["openai/z3-native-fixture"]}});
    let added = client
        .call(
            "T3ProviderUpsert",
            json!({"instanceId":id,"instance":desired,"expectedInstance":null}),
        )
        .await?;
    let created = instance(&added, &id)?["instance"].clone();
    let checks: Result<()> = async {
        for row in original["instances"]
            .as_array()
            .context("missing original list")?
        {
            let original_id = row["instanceId"].as_str().context("provider id missing")?;
            ensure!(
                instance(&added, original_id)?["instance"] == row["instance"],
                "unrelated provider changed"
            );
        }
        ensure!(
            created["config"]["customModels"] == desired["config"]["customModels"],
            "custom models were lost"
        );
        let mut edited = created.clone();
        edited["displayName"] = json!("Renamed native provider QA");
        let updated = client
            .call(
                "T3ProviderUpsert",
                json!({"instanceId":id,"instance":edited,"expectedInstance":created}),
            )
            .await?;
        ensure!(
            instance(&updated, &id)?["instance"]["displayName"] == edited["displayName"],
            "provider rename did not persist"
        );
        ensure!(
            client
                .call(
                    "T3ProviderUpsert",
                    json!({"instanceId":id,"instance":created,"expectedInstance":created})
                )
                .await
                .is_err(),
            "stale edit was accepted"
        );
        Ok(())
    }
    .await;
    // Remove even after a failed assertion; this name was generated by this run.
    let latest = client.call("T3ProvidersGet", json!({})).await?;
    let actual = instance(&latest, &id)?["instance"].clone();
    let removed = client
        .call(
            "T3ProviderRemove",
            json!({"instanceId":id,"expectedInstance":actual}),
        )
        .await?;
    ensure!(
        !removed["instances"]
            .as_array()
            .context("missing final list")?
            .iter()
            .any(|row| row["instanceId"] == id),
        "provider removal did not persist"
    );
    checks?;
    println!(
        "Native provider add/edit/remove, custom models, unrelated config preservation and stale-edit protection passed."
    );
    Ok(())
}
